---
# tasks file for ansible-test-popdsldap

- name: stop slapd
  become: true
  systemd:
    name: slapd
    state: stopped

## initialize slapd db files
- name: remove default db files
  become: true
  file:
    path="{{ item }}"
    state="absent"
  with_items:
    - "{{ popdsldap_removal_filepath }}"
  when: popdsldap_init

## create directories for slapd db files
- name: create new directories
  become: true
  file:
    path="{{ item.path }}"
    owner="{{ item.owner }}"
    group="{{ item.group }}"
    mode="{{ item.mode }}"
    state="directory"
  with_items:
    - "{{ popdsldap_add_dirinfo }}"

- name: start slapd
  become: true
  systemd:
    name: slapd
    state: started

# add some schema to slapd
- name: add some schema files
  shell: ldapadd -Q -Y EXTERNAL -H ldapi:/// -f "/etc/ldap/schema/{{ item }}.ldif"
  become: true
  ignore_errors: true
  with_items:
    - "{{ popdsldap_additional_schema }}"

# copy ldif files to remote
- name: copy ldif module to remote server
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{ item }}"
    owner: "{{ popdsldap_copy_ldif_perms.owner }}"
    group: "{{ popdsldap_copy_ldif_perms.group }}"
    mode:  "{{ popdsldap_copy_ldif_perms.mode }}"
  with_items:
    - "{{ popdsldap_copy_ldif_files }}"

#####################################
# setup toplevel organization entry #
#####################################
# ldapadd on cn=config
- name: ldapadd cn=config with some files
  become: true
  shell: ldapadd -Q -Y EXTERNAL -H ldapi:/// -f "/tmp/{{ item }}"
  register: result
  ignore_errors: True
  with_items:
    - "{{ popdsldap_ldapadd_cn_config_files }}"

####################
# populate dataset #
####################

- name: ldapadd on backend-db
  become: true
  shell: ldapadd -x -D "{{ popdsldap_cn_admin_dnprefix }},{{ popdsldap_basedn }}" -w "{{ popdsldap_cn_admin_password }}" -f "/tmp/{{ item }}"
  register: result
  ignore_errors: True
  with_items:
    - "{{ popdsldap_ldapadd_backenddb_files }}"

## end
